name: GitHub Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
  push_request:
    branches: [ "main" ]

jobs:
  buil-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dbt
        run: |
        pip install dbt
        dbt deps
