name: GitHub Continuous Integration

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  # Replace pull_request with pull_request_target if you
  # plan to use this action with forks, see the Limitations section
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8

      # Install your linters here
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          black: true
          black_auto_fix: true
          flake8: true
          flake8_auto_fix: false

      #SQL Fluff
      - name: SQL Fluff
        uses: yu-iskw/action-sqlfluff@v3
        id: lint-sql

      # Install dbt
      - name: Install dbt
        run: pip install dbt-duckdb dbt-duckdb[glue]
      - name: Deploy & test Models (CI)
        run: dbt build --profiles-dir . --target ci
