name: simple
prefect-version: 3.0.0

build: null

push:
  - prefect.deployments.steps.git_clone:
      repository: git@github.com:francisaddae/data_eng.git
      branch:
        - main
        - staging
      # access_token: "{{ prefect.blocks.secret.simple-github-pat }}"

pull:
  - prefect.deployments.steps.git_clone:
      repository: git@github.com:francisaddae/data_eng.git
      branch:
        - main
        - staging
      # access_token: "{{ prefect.blocks.secret.simple-github-pat }}"

deployments:
  - name: Main Flow
    description: A Flow Examples
    entrypoint: data_flow/flow.py
    parameters: {}
    schedule: {}
    work_pool:
      job_variables:
        image: prefecthq/prefect:3-latest
      name: flow-pool
